
spring:
  servlet:
    multipart:
      maxRequestSize: 10MB
      maxFileSize: 10MB
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect # MySQL에 맞는 방언 사용
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://chatbotdb.mysql.database.azure.com:3306/chatbot?useSSL=true
#    myDbConn: DriverManager.getConnection(url, "rlawogur0208", "jaehyoek02!");
    username : 'rlawogur0208'
    password : 'jaehyoek02!'
server:
  port: 8080
  ssl:
    key-store-type: PKCS12
    key-store: keystore.p12
    key-store-password: 1234
    key-alias: passion3.sktchatbot.kr # alias 이름 확인이 필요할 수 있습니다.