name: Build and Deploy Docker Image
on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew
    
    - name: Build Spring Boot application
      run: ./gradlew clean build  # 또는 해당 빌드 명령어로 변경

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}  # GitHub Secrets에 설정한 사용자명
        password: ${{ secrets.DOCKERHUB_TOKEN }}     # GitHub Secrets에 설정한 액세스 토큰

    - name: Build and push Docker image
      run: |
        docker build -t jaehyuk00/passin3backend:${{ github.sha }} .
        docker push jaehyuk00/passin3backend:${{ github.sha }}
